build:
  pullSecret: eap-pull-secret
  uri: https://github.com/wildfly-extras/first-responder-demo
  ref: main
  enabled: true
  mode: s2i
  output:
    kind: ImageStreamTag
  env:
      - name: MAVEN_ARGS_APPEND
        value: "-DskipTests -DfailOnMissingWebXml=false -Dquarkus.container-image.push=false -pl !simulator"
      - name: POSTGRESQL_DRIVER_VERSION
        value: '42.2.19'
  s2i:
    featurePacks:
      - org.jboss.eap:eap-datasources-galleon-pack:7.4.0.GA-redhat-00003
    galleonLayers:
      - cloud-server
      - postgresql-datasource
    amd64:
      version: latest
      jdk: "11"
      jdk11:
        builderImage: registry.redhat.io/jboss-eap-7/eap-xp4-openjdk11-openshift-rhel8
        runtimeImage: registry.redhat.io/jboss-eap-7/eap-xp4-openjdk11-runtime-openshift-rhel8
deploy:
  enabled: true
  livenessProbe:
    httpGet:
      path: /health/live
      port: admin
    initialDelaySeconds: 60
  readinessProbe:
    httpGet:
      path: /health/ready
      port: admin
    initialDelaySeconds: 60
  replicas: 1
  route:
    enabled: true
    tls:
      enabled: true
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
  env:
    # Env vars to connect to PostgreSQL DB
    - name: POSTGRESQL_DATABASE
      valueFrom:
        secretKeyRef:
          key: database-name
          name: frtest
    - name: POSTGRESQL_USER
      valueFrom:
        secretKeyRef:
          key: database-user
          name: frtest
    - name: POSTGRESQL_PASSWORD
      valueFrom:
        secretKeyRef:
          key: database-password
          name: frtest
    - name: POSTGRESQL_DATASOURCE
      value: frtest
    - name: POSTGRESQL_SERVICE_HOST
      value: frtest
    - name: POSTGRESQL_SERVICE_PORT
      value: "5432"  
image:
  tag: latest
